services:
  unmess-dev:
    container_name: unmess-dev
    #    platform: linux/amd64
    image: unmess-service:latest
    build:
      context: .
      ssh:
        - default
    restart: unless-stopped
    entrypoint: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/anton/code
    working_dir: /anton/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=TRUE
      - DJANGO_LOG_LEVEL=DEBUG
      - CACHE_ENABLED=TRUE
    env_file:
      - .env

  unmess:
    container_name: unmess
    entrypoint: gunicorn app.wsgi --bind=0.0.0.0:8000 --workers=2 -k gevent --log-level=debug --log-file=- --access-logfile=-
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=FALSE
      - CACHE_ENABLED=TRUE
      - DJANGO_LOG_LEVEL=INFO