# Generated by Django 4.2.11 on 2024-07-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_tvshow"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteriorDesigner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("years_of_experience", models.PositiveIntegerField()),
                (
                    "specialties",
                    models.CharField(
                        help_text="Comma-separated list of specialties", max_length=255
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "portfolio",
                    models.URLField(
                        blank=True, help_text="Link to portfolio", null=True
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Interior Designer",
                "verbose_name_plural": "Interior Designers",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.DeleteModel(
            name="Movie",
        ),
        migrations.DeleteModel(
            name="TVShow",
        ),
    ]
